// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwEQTC3VE8e5qUoTTtfdg2Pz14hc3Nr-Y',
    appId: '1:281064565914:web:0f2e45c9ec88bdf62cc323',
    messagingSenderId: '281064565914',
    projectId: 'gymboo-95709',
    authDomain: 'gymboo-95709.firebaseapp.com',
    storageBucket: 'gymboo-95709.firebasestorage.app',
    measurementId: 'G-NWVDFLLJSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJrysQsyatO-loFEYuEK_A46OQZXR638M',
    appId: '1:281064565914:android:a4b27389cfbae1732cc323',
    messagingSenderId: '281064565914',
    projectId: 'gymboo-95709',
    storageBucket: 'gymboo-95709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEzd5ML88oiSrGPWV-MvBfq6QQG8o7eh8',
    appId: '1:281064565914:ios:5c5fc8d2ffcc86c52cc323',
    messagingSenderId: '281064565914',
    projectId: 'gymboo-95709',
    storageBucket: 'gymboo-95709.firebasestorage.app',
    iosBundleId: 'com.example.gymbooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEzd5ML88oiSrGPWV-MvBfq6QQG8o7eh8',
    appId: '1:281064565914:ios:5c5fc8d2ffcc86c52cc323',
    messagingSenderId: '281064565914',
    projectId: 'gymboo-95709',
    storageBucket: 'gymboo-95709.firebasestorage.app',
    iosBundleId: 'com.example.gymbooApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwEQTC3VE8e5qUoTTtfdg2Pz14hc3Nr-Y',
    appId: '1:281064565914:web:8038c79fe9371d7f2cc323',
    messagingSenderId: '281064565914',
    projectId: 'gymboo-95709',
    authDomain: 'gymboo-95709.firebaseapp.com',
    storageBucket: 'gymboo-95709.firebasestorage.app',
    measurementId: 'G-TLPPZGZ10L',
  );
}
